void showBoard();
void restartGame();
void pushX(char row, char column);
void pushO(char row, char column);
bool checkValidSpot(char row, char column);
int checkGameStatus();
bool checkIfUndefined();
bool checkIfInvalid();
bool checkIfATie();
int checkIfWinner();